### ISSUE TITLE
老哥,你以前的effective java的在线阅读的仓库咋没了?

### ISSUE THREAD

**Issue by hebo6** [sjsdfg/OnJava8-Examples-Maven#1]
以前的链接: https://sjsdfg.github.io/effective-java-3rd-chinese/#/README

**Comment by sjsdfg** [comment]
被出版社发律师函了。下线了

**Comment by hebo6** [comment]
可惜了，你的effictive java的阅读体验简直不要太好。方便加一下微信聊聊吗？13155728271。

**Comment by zongxiaomi** [comment]
有fork 的吗 ，麻烦发我一下

**Comment by DcJiang1024** [comment]
可以私发下吗

**Comment by yuncitys-2** [comment]
可以私发下吗，非常感谢，qq  857239797 AT QQ。COM

**Comment by ChendayUP** [comment]
麻烦私下发下, 十分感谢  qq 705285647@qq.com

**Comment by AWeng0526** [comment]
麻烦私下发下, 十分感谢1154598143@qq.com

**Comment by JerryQiang** [comment]
老哥们，能发我一份嘛？

**Comment by jerryqiang** [comment]
老哥们，能发我一份嘛？
1131233593@qq.com
